### ISSUE TITLE
QuEST Valuation crashing

### ISSUE THREAD

**Issue by KevinXo** [rconcep/snl-quest#11]
Dear sir ,
 I have downloaded CAISO data about 201901.When I start Wiard or single run,it will crash.what should I do?

**Comment by KevinXo** [comment]
Dear sir,
WHEN I RUN Wizard,this happed
[INFO   ] [DataManager ] Data bank scan complete.
[INFO   ] [ValuationWizard] ISO changed to CAISO.
[INFO   ] [ValuationWizard] Pricing node changed to DGAP_EPE-APND (ID: DGAP_EPE-APND).
[INFO   ] [ValuationWizard] Market formulation changed to Arbitrage.
[INFO   ] [ValuationWizard] Changed historical data set to 2019.
[INFO   ] [ValuationWizard] Energy storage device changed to Li-ion Battery.
[INFO   ] [DMS         ] Data not yet in DMS, loading...
[INFO   ] [DMS         ] Saving valuation_dms.p.
[INFO   ] [DMS         ] Saving valuation_dms.p.
[INFO   ] [DMS         ] Saving valuation_dms.p.
[INFO   ] [DMS         ] Saving valuation_dms.p.
[INFO   ] [DMS         ] Saving valuation_dms.p.
[INFO   ] [DMS         ] Saving valuation_dms.p.
[INFO   ] [DMS         ] Saving valuation_dms.p.
[INFO   ] [DMS         ] Saving valuation_dms.p.
[INFO   ] [DMS         ] Saving valuation_dms.p.
[INFO   ] [Optimizer   ] Setting Power_rating to 36.0
[INFO   ] [Optimizer   ] Setting Energy_capacity to 24.0
[INFO   ] [Optimizer   ] Setting Round_trip_efficiency to 90.0
[INFO   ] [Optimizer   ] Setting Self_discharge_efficiency to 100.0
[WARNING] [ValuationOptimizer] Self_discharge_efficiency provided is greater than 1.0, interpreting as percentage...
[WARNING] [ValuationOptimizer] Round_trip_efficiency provided is greater than 1.0, interpreting as percentage...
  File "<stdin>", line 3
SyntaxError: Non-ASCII character '\xe5' in file <stdin> on line 3, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
ERROR: Solver (gurobi) returned non-zero return code (1)
ERROR: See the solver log above for diagnostic information.
[ERROR  ] [ValOp Handler] Something went wrong when solving: (Solver (gurobi) did not exit normally)
[INFO   ] [ValOp Handler] Finished processing requested jobs.

What should I do?

**Comment by rconcep** [comment]
Hello,
I tried downloading data for that pricing node (DGAP_EPE-APND) and it doesn't seem to exist. Could you describe how you downloaded the data so that I can try to replicate the issue?

**Comment by KevinXo** [comment]
Hello,
After I changed the sovler,the problem has been solved. Data for (DGAP_EPE-APND) is contained in CAISO data about 201901.
