### ISSUE TITLE
Cannot locate the 'glpsol' executable

### ISSUE THREAD

**Issue by jgillis91** [rconcep/snl-quest#21]
I've just downloaded v1.2.e. When I run the valuation tool, I am told that solver glpk cannot find glpsol. Is there a fix for this?

**Comment by rconcep** [comment]
Hello,

For running analyses like in QuESt Valuation, you will need to also install a solver for the optimization and GLPK is one of the solver options. There are some instructions for installing GLPK in the Readme (see: "Solvers compatible with Pyomo"). 

Regardless if you install QuESt from source code or are using the packaged executable releases you will need a solver. QuESt will launch and you can do other tasks like download data through QuESt Data Manager without a solver installed. However, you will not be able to complete analyses without one as you experienced.

Let me know if you need clarification on the installation process.

**Comment by jgillis91** [comment]
Thanks! Got everything up and running. Very helpful model.

**Comment by rconcep** [comment]
Great to hear, thanks!
